package com.learning.demo.dal.model;

import java.io.Serializable;
import java.util.Date;

public class UserInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.ID
     *
     * @mbg.generated Mon Jul 03 21:38:38 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.NAME
     *
     * @mbg.generated Mon Jul 03 21:38:38 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.AGE
     *
     * @mbg.generated Mon Jul 03 21:38:38 CST 2017
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.BIRTHDATE
     *
     * @mbg.generated Mon Jul 03 21:38:38 CST 2017
     */
    private Date birthdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_info
     *
     * @mbg.generated Mon Jul 03 21:38:38 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.ID
     *
     * @return the value of user_info.ID
     *
     * @mbg.generated Mon Jul 03 21:38:38 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.ID
     *
     * @param id the value for user_info.ID
     *
     * @mbg.generated Mon Jul 03 21:38:38 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.NAME
     *
     * @return the value of user_info.NAME
     *
     * @mbg.generated Mon Jul 03 21:38:38 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.NAME
     *
     * @param name the value for user_info.NAME
     *
     * @mbg.generated Mon Jul 03 21:38:38 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.AGE
     *
     * @return the value of user_info.AGE
     *
     * @mbg.generated Mon Jul 03 21:38:38 CST 2017
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.AGE
     *
     * @param age the value for user_info.AGE
     *
     * @mbg.generated Mon Jul 03 21:38:38 CST 2017
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.BIRTHDATE
     *
     * @return the value of user_info.BIRTHDATE
     *
     * @mbg.generated Mon Jul 03 21:38:38 CST 2017
     */
    public Date getBirthdate() {
        return birthdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.BIRTHDATE
     *
     * @param birthdate the value for user_info.BIRTHDATE
     *
     * @mbg.generated Mon Jul 03 21:38:38 CST 2017
     */
    public void setBirthdate(Date birthdate) {
        this.birthdate = birthdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Mon Jul 03 21:38:38 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", age=").append(age);
        sb.append(", birthdate=").append(birthdate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}